const questions = [
  { question: "Communication channel is shared by all the machines on the network in", options: ["Broadcast network", "Unicast network", "Multicast network", "None of the above"], answer: 0 },
  { question: "A _____ is a device that forwards packets between networks by processing the routing information included in the packet.", options: ["Bridge", "Firewall", "Router", "All of the above"], answer: 2 },
  { question: "Network congestion occurs", options: ["In case of traffic overloading", "When a system terminates", "When connection between two nodes terminates", "None of the above"], answer: 0 },
  { question: "UTP is commonly used in", options: ["DSL (Digital Subscriber Lines)", "FTTP", "HTTP", "None of the above"], answer: 0 },
  { question: "Coaxial cable consists _____ concentric copper conductors", options: ["1", "2", "3", "4"], answer: 1 },
  { question: "Geostationary satellites", options: ["Are placed at a fixed point above the earth", "Rotate the earth about a fixed axis", "Rotate the earth about a varying axis", "None of the above"], answer: 0 },
  { question: "Dynamic web page", options: ["Is same everytime whenever it displays", "Generates on demand by a program or a request from browser", "Both (A) and (B)", "None of the above"], answer: 1 },
  { question: "URL stands for", options: ["Unique reference label", "Uniform resource locator", "Uniform reference label", "Unique resource locator"], answer: 1 },
  { question: "HTTP is _____ protocol", options: ["Application layer", "Transport layer", "Networks layer", "None of the above"], answer: 0 },
  { question: "HTTP client request by establishing a connection to a particular part on the server", options: ["User diagram protocol", "Transmission control protocol", "Border gateway protocol", "None of the above"], answer: 1 },
  { question: "In FTP protocol, client contacts server with using _____ protocol as the transport", options: ["Transmission controls protocols", "User diagrams protocol", "Diagram congestion control", "Stream control transmission protocol"], answer: 0 },
  { question: "The file transfer protocol is built on", options: ["Data centric architecture", "Service oriented architecture", "Client server architecture", "None of the above"], answer: 2 },
  { question: "Ethernet frame consists of", options: ["IP address", "MAC address", "Both (A) and (B)", "None of the above"], answer: 1 },
  { question: "What is auto-negotiation?", options: ["A security algorithm", "A routing algorithm", "A procedure by which two connected devices choose common transmission parameters", "None of the above"], answer: 2 },
  { question: "High speed ethernet works on", options: ["Coaxial cable", "Twisted pair cable", "Optical fibre", "None of the above"], answer: 2 },
  { question: "The maximum size of payload field in ethernet frame is", options: ["1000 bytes", "1200 bytes", "1300 bytes", "1500 bytes"], answer: 3 },
  { question: "Physical or logical arrangements of networks is", options: ["Topology", "Routing", "Networking", "None of the above"], answer: 0 },
  { question: "An ethernet frame that is less than the IEEE 802.3 minimum length of 64 octets is called", options: ["Short frame", "Run frame", "Mini frame", "Manframe"], answer: 1 },
  { question: "In this topology there is a central controller or hub", options: ["Star", "Mesh", "Ring", "None of the above"], answer: 0 },
  { question: "Data communication system within a building or campus is", options: ["LAN", "WAN", "MAN", "None of the above"], answer: 0 },
  { question: "The header length of an IPv6 diagram is", options: ["10 bytes", "25 bytes", "30 bytes", "40 bytes"], answer: 3 },
  { question: "In the IPv6 header, the traffic class field is similar to which field in IPv4 header?", options: ["Fragmentation field", "Fast switching", "ToS field", "Option field"], answer: 2 },
  { question: "These are the features present in IPv4 but not IPv6", options: ["Fragmentation", "Header checksum", "Option", "All of the above"], answer: 3 },
  { question: "The _____ field determines the lifetimes of IPv6 diagram", options: ["TTL", "Hop limit", "Next header", "None of the above"], answer: 1 },
  { question: "Dual-stack approach refers to", options: ["Implementing IPv4 with 2 stacks", "Implementing IPv6 with 2 stacks", "Node has both IPv4 and IPv6 support", "None of the above"], answer: 2 },
  { question: "How is single channel shared by multiple signals in a computer network?", options: ["Multiplexing", "Phase modulation", "Analog modulation", "Digital modulation"], answer: 0 },
  { question: "Which layer does the data link layer take packets from and encapsulate them into frames for transmission?", options: ["Transport layer", "Application layer", "Network layer", "Physical layer"], answer: 2 },
  { question: "Which type of network shares the communication channel among all the machines?", options: ["Anycast networks", "Multicast network", "Unicast network", "Broadcast network"], answer: 3 },
  { question: "Which topology requires a multipoint connection?", options: ["Ring", "Bus", "Star", "Mesh"], answer: 1 },
  { question: "Which of the following maintains the domain name system?", options: ["A single server", "A single computer", "Distributed database system", "None of the above"], answer: 2 },
  { question: "The packet of information at the application layer is called", options: ["Packet", "Message", "Segment", "Frame"], answer: 1 },
  { question: "This is one of the architecture paradigm", options: ["Peer to peer", "Client-server", "HTTP", "Both (A) and (B)"], answer: 3 },
  { question: "Application layer offers _____ service", options: ["End to end", "Process to process", "Both (A) and (B)", "None of the above"], answer: 1 },
  { question: "E-mail is?", options: ["Loss tolerant application", "Bandwidth-sensitive application", "Elastic application", "None of the above"], answer: 2 },
  { question: "Transport services available to application in one or another form", options: ["Reliable data transfer", "Timing", "Security", "All of the above"], answer: 3 },
  { question: "Electronic mail uses this application layer protocol", options: ["SMTP", "HTTP", "FTP", "SIP"], answer: 0 },
  { question: "The number of objects in a web page which consists of 4 jpeg images and HTML text is", options: ["4", "1", "5", "None of the above"], answer: 2 },
  { question: "The default connection type used by HTTP is", options: ["Persistent", "Not persistent", "Either of the above", "None of the above"], answer: 0 },
  { question: "The time taken by a packet to travel from a client to server and then back to the client is called", options: ["STT", "RTT", "PTT", "None of the above"], answer: 1 },
  { question: "The value GET, POST, HEAD etc are specified in", options: ["Header line", "Status line", "Request line", "Entity body"], answer: 2 },
  { question: "The HTTP response message leaves out the requested object when _____ method is used", options: ["GET", "POST", "HEAD", "PUT"], answer: 2 },
  { question: "Which of the following is not correct?", options: ["Web cache does not have its own disk space", "Web cache can act both like server and client", "Web cache might reduce the response time", "Web cache contains copies of recently requested objects"], answer: 0 },
  { question: "Which of the following is present in both an HTTP request line and a status line?", options: ["HTTP version number", "URL", "Method", "None of the above"], answer: 0 },
  { question: "Expansion of FTP is", options: ["Fine Transfer Protocol", "File transfer protocol", "First transfer protocol", "None of the above"], answer: 1 },
  { question: "The commands from client to server are sent across the control connection in _____ bit ASCII format", options: ["8", "7", "3", "5"], answer: 1 },
  { question: "The password is sent to the server using _____ command", options: ["PASSWD", "PASS", "PASSWORD", "None of the above"], answer: 1 },
  { question: "Unsolicited commercial email is known as", options: ["Malware", "Virus", "Spyware", "Spam"], answer: 3 },
  { question: "Choose the options which come under the category of net etiquettes: (1) Be Ethical (2) Respect privacy (3) Be responsible (4) Be respectful", options: ["1, 2, 3 and 4", "1 only", "2 only", "3 and 4 only"], answer: 0 },
  { question: "The two types of digital footprints are (1) Tech (2) Smart (3) Passive (4) Active", options: ["1 and 4 only", "2 and 3 only", "1, 2, 3 and 4", "3 and 4 only"], answer: 3 },
  { question: "Anyone who uses digital technology along with internet is known as: (1) Netizen (2) Digital citizen", options: ["1 and 2 only", "3 and 4 only", "2 and 4 only", "1 and 4 only"], answer: 2 },
  { question: "What is the purpose of enabling passwords on a PC?", options: ["For improving the data signal strength", "For providing an additional layer of security", "For reducing the installed application", "For printing of the data in the PC"], answer: 1 },
  { question: "In computing, _____ is a network security system that monitors and controls incoming and outgoing network traffic", options: ["Spyware", "Cookie", "Spam", "Firewalls"], answer: 3 },
  { question: "What is the term for a cyber security attack that targets multiple interconnected devices to create a large-scale attack network?", options: ["DDOS attack", "Botnet attack", "Zero day attack", "Spear phishing attack"], answer: 1 },
  { question: "A Computer virus is a", options: ["Hardware", "Software", "Bacteria", "Freeware"], answer: 1 },
  { question: "Knowing the password of a user for hacking is called", options: ["Sneaking", "Spoofing", "Cyber stalking", "Spamming"], answer: 1 },
  { question: "Which type of virus attacks EXE files and the infected EXE files attack other EXE files?", options: ["Stealth Virus", "Root sector virus", "Parasitic virus", "Memory resident virus"], answer: 2 },
  { question: "Symmetric encryption is also known as:", options: ["Conventional encryption", "Asymmetric encryption", "Public key encryption", "Hybrid encryption"], answer: 0 },
  { question: "Which of the following is an attack in which the user receives unwanted amount of emails?", options: ["Email bomb", "Ping Storm", "Spoofing", "Smurfing"], answer: 0 },
  { question: "Which is not an objective of network security?", options: ["Identification", "Authentification", "Access controls", "Lock"], answer: 3 },
  { question: "Which of these is a part of network identification?", options: ["User ID", "Password", "OTP", "Fingerprint"], answer: 0 },
  { question: "A concern of authentication that deals with user rights:", options: ["General Access", "Functional authentication", "Functional authorization", "Auto verification"], answer: 2 },
  { question: "The method of breaking a large message into smaller packets for transmission is:", options: ["Encapsulation", "Fragmentation", "Segmentation", "Multiplexing"], answer: 2 },
  { question: "Which protocol is used to map an IP address to a physical MAC address?", options: ["RARP", "ARP", "ICMP", "IGMP"], answer: 1 },
  { question: "The process of converting plain text into an unreadable format is called:", options: ["Decryption", "Encryption", "Encoding", "Hashing"], answer: 1 },
  { question: "A network that connects devices within a city is known as:", options: ["LAN", "WAN", "MAN", "PAN"], answer: 2 },
  { question: "Which of the following is a private IP address?", options: ["192.168.1.1", "172.16.0.1", "10.0.0.1", "All of the above"], answer: 3 },
  { question: "The Three-Way Handshake is a feature of which protocol?", options: ["UDP", "TCP", "HTTP", "FTP"], answer: 1 },
  { question: "Which layer of the OSI model handles error detection and correction?", options: ["Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer"], answer: 1 },
  { question: "In a mesh topology, the number of dedicated links for n devices is:", options: ["n(n-1)", "n(n-1)/2", "n", "n+1"], answer: 1 },
  { question: "Which device operates primarily at the Physical layer?", options: ["Hub", "Switch", "Router", "Bridge"], answer: 0 },
  { question: "Telnet is a _____ based network protocol.", options: ["Text", "Graphic", "Sound", "Video"], answer: 0 },
  { question: "What is the maximum data rate of a standard 10Base-T Ethernet?", options: ["1 Mbps", "10 Mbps", "100 Mbps", "1000 Mbps"], answer: 1 },
  { question: "DNS is used to translate _____ into IP addresses.", options: ["MAC addresses", "Domain names", "Port numbers", "File names"], answer: 1 },
  { question: "The protocol used for retrieving emails from a mail server is:", options: ["SMTP", "POP3", "SNMP", "Telnet"], answer: 1 },
  { question: "Which protocol provides a connectionless service at the transport layer?", options: ["TCP", "UDP", "IP", "HTTP"], answer: 1 },
  { question: "IPv4 addresses have a length of _____ bits.", options: ["32 bits", "64 bits", "128 bits", "16 bits"], answer: 0 },
  { question: "A _____ is a combination of an IP address and a port number.", options: ["Socket", "Packet", "Frame", "Header"], answer: 0 },
  { question: "Which layer of the OSI model is responsible for compression and encryption?", options: ["Application Layer", "Presentation Layer", "Session Layer", "Transport Layer"], answer: 1 },
  { question: "What does ICMP stand for?", options: ["Internet Control Message Protocol", "Internal Control Management Protocol", "Internet Connection Message Protocol", "Inter-network Control Management Protocol"], answer: 0 },
  { question: "A repeater works in the _____ layer of the OSI model.", options: ["Network", "Physical", "Data Link", "Transport"], answer: 1 },
  { question: "Which field in the IP header is used to prevent packets from looping infinitely?", options: ["Checksum", "Time to Live (TTL)", "Source IP", "Header Length"], answer: 1 },
  { question: "Transmission media is usually categorized as:", options: ["Fixed and unfixed", "Guided and unguided", "Wired and wireless", "Both (B) and (C)"], answer: 3 },
  { question: "Which protocol is used for remote login?", options: ["HTTP", "FTP", "Telnet", "SMTP"], answer: 2 },
  { question: "The process of finding the best path for a packet is called:", options: ["Switching", "Routing", "Bridging", "Forwarding"], answer: 1 },
  { question: "A bridge operates at which layer of the OSI model?", options: ["Physical", "Data Link", "Network", "Transport"], answer: 1 },
  { question: "Cookies are used to:", options: ["Store user passwords on the server", "Store user-side information to track sessions", "Delete temporary files", "Protect against viruses"], answer: 1 },
  { question: "What is the standard port number for HTTP?", options: ["21", "25", "80", "443"], answer: 2 },
  { question: "The 128-bit address used in IPv6 is written in:", options: ["Decimal", "Binary", "Hexadecimal", "Octal"], answer: 2 },
  { question: "Which protocol is used to transfer files between a client and a server?", options: ["HTTP", "SMTP", "FTP", "SNMP"], answer: 2 },
  { question: "A Denial of Service (DoS) attack is intended to:", options: ["Steal passwords", "Crash a system or make it unavailable", "Monitor network traffic", "Encrypt user data"], answer: 1 },
  { question: "What is a Phishing attack?", options: ["Sending a virus via email", "Tricking users into providing sensitive information", "Overloading a server with requests", "Physical theft of a computer"], answer: 1 },
  { question: "In asymmetric encryption, if the public key is used for encryption, which key is used for decryption?", options: ["The same public key", "The private key", "A secret key", "No key is needed"], answer: 1 },
  { question: "Which topology uses a single backbone cable to which all nodes are connected?", options: ["Star", "Bus", "Ring", "Mesh"], answer: 1 },
  { question: "The term Bandwidth refers to:", options: ["The speed of the processor", "The capacity of a communication channel", "The length of the cable", "The size of the hard drive"], answer: 1 },
  { question: "Which protocol is used to automatically assign IP addresses to devices?", options: ["DNS", "DHCP", "ARP", "ICMP"], answer: 1 },
  { question: "HTTPS is a secure version of HTTP that uses:", options: ["SSH", "SSL/TLS", "FTP", "SMTP"], answer: 1 },
  { question: "What is the purpose of a proxy server?", options: ["To speed up network access by caching", "To provide anonymity", "To act as a firewall", "All of the above"], answer: 3 },
  { question: "A Worm differs from a Virus because it:", options: ["Does not require a host program to spread", "Only attacks hardware", "Is always harmless", "Cannot spread over a network"], answer: 0 },
  { question: "The Presentation Layer is also known as the:", options: ["Syntax layer", "Semantic layer", "Dialogue layer", "Both (A) and (B)"], answer: 3 },
  { question: "The layer closest to the transmission medium is the:", options: ["Application Layer", "Transport Layer", "Network Layer", "Physical Layer"], answer: 3 },
  { question: "Which layer of the OSI model is responsible for routing packets?", options: ["Data Link Layer", "Transport Layer", "Network Layer", "Session Layer"], answer: 2 },
  { question: "What does the acronym HTTPS stand for?", options: ["HyperText Transfer Protocol Standard", "HyperText Transfer Protocol Secure", "High Transfer Text Protocol Secure", "HyperText Transport Protocol System"], answer: 1 },
  { question: "Which port number is used by DNS?", options: ["21", "80", "53", "143"], answer: 2 },
  { question: "TCP 3-way handshake involves which sequence?", options: ["SYN-ACK-SYN-ACK", "ACK-SYN-SYN-ACK", "SYN-SYN-ACK-ACK", "SYN-ACK-SYN-ACK"], answer: 2 },
  { question: "Which class of IP addresses has the default subnet mask 255.255.0.0?", options: ["Class A", "Class B", "Class C", "Class D"], answer: 1 },
  { question: "What is the maximum number of hops allowed in RIP?", options: ["10", "255", "15", "32"], answer: 2 },
  { question: "Which device operates at Layer 2 of the OSI model and uses MAC addresses?", options: ["Hub", "Router", "Switch", "Repeater"], answer: 2 },
  { question: "Which protocol automatically assigns IP addresses to devices on a network?", options: ["ARP", "RARP", "ICMP", "DHCP"], answer: 3 },
  { question: "In IPv6, how many bits are used for addressing?", options: ["32", "64", "128", "256"], answer: 2 },
  { question: "Which transmission mode allows communication in both directions simultaneously?", options: ["Simplex", "Half-Duplex", "Full-Duplex", "Multiplex"], answer: 2 },
  { question: "The error detection technique that uses polynomial division is called:", options: ["Parity Check", "Checksum", "Hamming Code", "CRC"], answer: 3 },
  { question: "What does ARP stand for and what does it resolve?", options: ["Address Resolution Protocol; IP to MAC", "Address Resolution Protocol; MAC to IP", "Automatic Routing Protocol; IP to MAC", "Address Routing Protocol; domain to IP"], answer: 0 },
  { question: "Which Wi-Fi standard supports speeds up to 9.6 Gbps and is known as Wi-Fi 6?", options: ["IEEE 802.11n", "IEEE 802.11ac", "IEEE 802.11ax", "IEEE 802.11g"], answer: 2 },
  { question: "In network topologies, the total number of links in a full mesh with n nodes is:", options: ["n squared", "n(n+1)/2", "n(n-1)/2", "n-1"], answer: 2 },
  { question: "Which protocol is used by ping and traceroute utilities?", options: ["TCP", "UDP", "ICMP", "ARP"], answer: 2 },
  { question: "The CIA Triad in cyber security does NOT include:", options: ["Confidentiality", "Integrity", "Authentication", "Availability"], answer: 2 },
  { question: "Which type of malware disguises itself as legitimate software but does NOT self-replicate?", options: ["Virus", "Worm", "Trojan Horse", "Ransomware"], answer: 2 },
  { question: "AES (Advanced Encryption Standard) is an example of:", options: ["Asymmetric encryption", "Symmetric encryption", "Hashing algorithm", "Digital signature scheme"], answer: 1 },
  { question: "Which attack involves injecting malicious SQL code into an input field to manipulate a database?", options: ["XSS", "CSRF", "SQL Injection", "Buffer Overflow"], answer: 2 },
  { question: "Under which section of the IT Act 2000 is cyber terrorism covered?", options: ["Section 66", "Section 66C", "Section 67", "Section 66F"], answer: 3 },
  { question: "Which hashing algorithm produces a 128-bit hash value?", options: ["SHA-1", "SHA-256", "MD5", "SHA-512"], answer: 2 },
  { question: "A digital signature is created by encrypting the message hash with the sender's:", options: ["Public key", "Private key", "Session key", "Shared key"], answer: 1 },
  { question: "Which access control model is based on job roles?", options: ["DAC", "MAC", "RBAC", "ABAC"], answer: 2 },
  { question: "The WannaCry attack of 2017 was primarily which type of malware?", options: ["Spyware", "Ransomware", "Adware", "Rootkit"], answer: 1 },
  { question: "In penetration testing, black box testing means:", options: ["Full knowledge of target system", "Partial knowledge of target", "No prior knowledge of target", "Testing with source code access"], answer: 2 },
  { question: "Which of the following is a connectionless transport protocol?", options: ["TCP", "FTP", "UDP", "HTTP"], answer: 2 },
  { question: "The DHCP process follows which sequence?", options: ["DORA (Discover, Offer, Request, Acknowledge)", "ROAD (Request, Offer, Acknowledge, Discover)", "OARD (Offer, Acknowledge, Request, Discover)", "RADO (Request, Acknowledge, Discover, Offer)"], answer: 0 },
  { question: "Section 66A of the IT Act 2000 was struck down in which case?", options: ["Vishaka vs State of Rajasthan", "Shreya Singhal vs Union of India", "PUCL vs Union of India", "Maneka Gandhi vs Union of India"], answer: 1 },
  { question: "Which type of phishing attack targets senior executives like CEOs?", options: ["Spear Phishing", "Clone Phishing", "Whaling", "Vishing"], answer: 2 },
  { question: "RSA encryption is based on the mathematical difficulty of:", options: ["Discrete logarithm", "Elliptic curve", "Prime factorization of large numbers", "Polynomial interpolation"], answer: 2 },
  { question: "What is the port number used by SSH (Secure Shell)?", options: ["21", "22", "23", "25"], answer: 1 },
  { question: "A Botnet is a network of:", options: ["Legitimate servers used for cloud computing", "Compromised computers controlled by an attacker", "Firewalls deployed to prevent attacks", "IoT devices for smart home automation"], answer: 1 },
  { question: "Which flow control protocol retransmits ONLY the specific erroneous frame?", options: ["Stop-and-Wait ARQ", "Go-Back-N ARQ", "Selective Repeat ARQ", "CSMA/CD"], answer: 2 },
  { question: "The IT Act 2000 was enacted on which date?", options: ["26 January 2000", "15 August 2000", "9 June 2000", "1 April 2000"], answer: 2 },
  { question: "Which network type covers a metropolitan area (city-wide)?", options: ["LAN", "WAN", "MAN", "PAN"], answer: 2 },
  { question: "In cyber forensics, the chain of custody refers to:", options: ["Encryption used to protect evidence", "Documentation of who handled digital evidence", "The order of volatility of evidence sources", "A linked list data structure used in forensic tools"], answer: 1 },
  { question: "Which protocol is used for sending emails?", options: ["POP3", "IMAP", "SMTP", "HTTP"], answer: 2 },
  { question: "An IPS differs from an IDS because it:", options: ["Only monitors traffic", "Actively blocks detected threats", "Only generates alerts", "Works at the physical layer"], answer: 1 },
  { question: "Which of the following is NOT a switching technique?", options: ["Circuit Switching", "Packet Switching", "Message Switching", "Frequency Switching"], answer: 3 },
  { question: "XSS attack primarily violates which CIA property?", options: ["Availability", "Integrity and Confidentiality", "Availability and Integrity", "Only Availability"], answer: 1 },
  { question: "The Hamming Code is used for:", options: ["Error detection only", "Error correction (single-bit errors)", "Data compression", "Encryption of data"], answer: 1 },
  { question: "Under Section 66C of the IT Act 2000, which offence is covered?", options: ["Hacking", "Cyber terrorism", "Identity theft", "Publishing obscene material"], answer: 2 },
  { question: "Which type of backup copies only files changed since the last FULL backup?", options: ["Incremental", "Differential", "Mirror", "Snapshot"], answer: 1 },
  { question: "NAT (Network Address Translation) is primarily used to:", options: ["Encrypt network traffic", "Map private IP addresses to public IPs", "Resolve domain names to IPs", "Detect network intrusions"], answer: 1 },
  { question: "A SYN flood attack is an example of which category of attack?", options: ["Phishing", "SQL Injection", "DoS/DDoS", "Man-in-the-Middle"], answer: 2 },
  { question: "Which multiplexing technique uses different light wavelengths in fiber optic networks?", options: ["TDM", "FDM", "WDM", "CDM"], answer: 2 },
  { question: "Which is a lightweight IoT messaging protocol that uses publish/subscribe model?", options: ["HTTP", "MQTT", "FTP", "SNMP"], answer: 1 },
  { question: "In public key cryptography, to send an encrypted message to someone, you use their:", options: ["Private key", "Your own public key", "Recipient's public key", "Shared secret key"], answer: 2 },
  { question: "OSPF routing protocol uses which algorithm to compute shortest paths?", options: ["Bellman-Ford", "Dijkstra's Algorithm", "Floyd-Warshall", "Kruskal's Algorithm"], answer: 1 },
  { question: "Which section of the IT Act 2000 provides safe harbour protection to intermediaries?", options: ["Section 43", "Section 66", "Section 72", "Section 79"], answer: 3 }
];
